supabase:
    url: ${SUPABASE_URL}
    anon: ${SUPABASE_ANON_KEY}
    jwt_secret: ${SUPABASE_JWT_SIGNER}
spring:
    application:
        name: Game
    datasource:
        url: ${SUPABASE_DATABASE_URL}
        username: ${SUPABASE_DATABASE_USER}
        password: ${SUPABASE_DATABASE_PASSWORD}
        driverClassName: org.postgresql.Driver
    jpa:
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                "[format_sql]": true
                jdbc:
                    lob:
                        "[non_contextual_creation]": true
        show-sql: true

